### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by amirouche** [amirouche/zk#3]
# v0.2

nothing yet!

# TODO

- [ ] `Ctrl+d` to delete the current character
- [ ] `Ctrl+t` to swap the current character with the previous
- [ ] `Ctrl+s` to save file
- [ ] `TAB` to auto-indent
- [ ] interactive mini-buffer
- [ ] custom color themes
- [ ] multiple modes support
- [ ] `Ctrl+c`, `Ctrl+v` and `Ctrl+x` support
- [ ] `Ctrl+k` to "kill" the rest of the line (maybe add it to the copy-paste buffer?)
- [ ] `Ctrl+z` to undo and `Ctrl+Shift+z` to redo
- [ ] select region
- [ ] interactive command support 
- [ ] `Ctrl+g` to exit current interactive command
- [ ] `Ctrl-f` to search
- [ ] `Ctrl+Shift+f` to search and replace
- [ ] backup file
- [ ] `Alt+x` to execute a procedure
- [ ] `Ctrl+KEY-LEFT` and `Ctrl+KEY-RIGHT` to speed up navigation of the buffer
- [ ] Support for multiple buffers
- [ ] Support for frames
- [ ] Support for mark and mark navigation across buffer and in the same buffer
- [ ] copy/paste from xorg
